services:
  nestjs_api:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
  db: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    ports:
      - 5432:5432